version: "3.8"
services:
  main_db:
    image: cezarpop/pakketmanagementrepo:...
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ...
    volumes:
      - ...

  authentication_db:
    image: cezarpop/pakketmanagementrepo:...
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ...
    volumes:
      - ...

  main_backend:
    image: cezarpop/pakketmanagementrepo:backend
    ports:
      - 8888:8080
    depends_on:
      - main_db

  authentication_backend:
    image: cezarpop/pakketmanagementrepo:authenticatiebackend
    ports:
      - 8887:8080
    depends_on:
      - authentication_db
  
  frontend:
    image: cezarpop/pakketmanagementrepo:frontend
    ports:
      - 3001:3000
    depends_on:
      - ...

  volumes:
    main_data:
      driver: local
    authentication_data:
      driver: local